fix: callback not being thrown on time out

