Bug fix: #379908
- to throw the exception the condition has to be denied
